<?php

// this file is auto-generated by prolic/fpp
// don't edit this file manually

declare(strict_types=1);

namespace TodoApp\Domain\Model\User;

final class UserPassword
{
    private $password;

    public function __construct(string $password)
    {
        $this->password = $password;
    }

    public function password(): string
    {
        return $this->password;
    }

    public function withPassword(string $password): UserPassword
    {
        return new self($password);
    }

    public static function fromString(string $password): UserPassword
    {
        return new self($password);
    }

    public function toString(): string
    {
        return $this->password;
    }

    public function __toString(): string
    {
        return $this->password;
    }
}
